logging:
  enabled: true
  log_file: logs/proxy_manager.log
  log_level: INFO
  max_bytes: 10485760
  backup_count: 7
  log_format: '%(asctime)s [%(levelname)s] [%(filename)s:%(lineno)d] %(message)s'
  date_format: '%Y-%m-%d %H:%M:%S'
regions:
- code: GB
  name: 英国
- code: SG
  name: 新加坡
- code: HK
  name: 香港
- code: MY
  name: 马来西亚
- code: PH
  name: 菲律宾
- code: FR
  name: 法国
vm_account_counters:
  Vinted_GB: 3
  Vinted_HK: 3
  Carousell_HK: 14
  Carousell_HK_72e8932c: 15
  Vinted_HK_72e8932c: 1
  Vinted_GB_72e8932c: 1
proxy_name_counters:
  HK: 171
  UK: 33
config_file_path: D:\app_uploader\config.yaml
vm_script_path: /data/local/tmp/vm.sh
adb_path: D:\桌面\platform-tools\adb.exe
vm_accounts_file_path: /data/local/tmp/multiapp_conf.txt
vm_model_config_path: /storage/emulated/0/MultiApp_Farm/Profiles/
devices:
- device_id: 72e8932c
  remark: HK2
- device_id: ad9accd8
  remark: HK4
current_device_id: 72e8932c
